In [1]:
#https://www.geeksforgeeks.org/snowflakes-fractal-using-python/
# Python code to draw snowflakes fractal. 
import turtle 
import random 

# setup the window with a background color 
wn = turtle.Screen() 
wn.bgcolor("cyan") 

# assign a name to your turtle 
elsa = turtle.Turtle() 
elsa.speed(15) 

# create a list of colours 
sfcolor = ["white", "blue", "purple", "grey", "magenta"] 

# create a function to create different size snowflakes 
def snowflake(size): 

	# move the pen into starting position 
	elsa.penup() 
	elsa.forward(10*size) 
	elsa.left(45) 
	elsa.pendown() 
	elsa.color(random.choice(sfcolor)) 

	# draw branch 8 times to make a snowflake 
	for i in range(8): 
		branch(size) 
		elsa.left(45) 
	

# create one branch of the snowflake 
def branch(size): 
	for i in range(3): 
		for i in range(3): 
			elsa.forward(10.0*size/3) 
			elsa.backward(10.0*size/3) 
			elsa.right(45) 
		elsa.left(90) 
		elsa.backward(10.0*size/3) 
		elsa.left(45) 
	elsa.right(90) 
	elsa.forward(10.0*size) 

# loop to create 20 different sized snowflakes 
# with different starting co-ordinates 
for i in range(20): 
	x = random.randint(-200, 200) 
	y = random.randint(-200, 200) 
	sf_size = random.randint(1, 4) 
	elsa.penup() 
	elsa.goto(x, y) 
	elsa.pendown() 
	snowflake(sf_size) 

# leave the window open until you click to close 
wn.exitonclick() 


In [2]:
#https://www.geeksforgeeks.org/python-sierpinski-carpet/
# importing necessary modules 
import numpy as np 
from PIL import Image 

# total number of times the process will be repeated 
total = 7

# size of the image 
size = 3**total 

# creating an image 
square = np.empty([size, size, 3], dtype = np.uint8) 
color = np.array([255, 255, 255], dtype = np.uint8) 

# filling it black 
square.fill(0) 

for i in range(0, total + 1): 
	stepdown = 3**(total - i) 
	for x in range(0, 3**i): 
		
		# checking for the centremost square 
		if x % 3 == 1: 
			for y in range(0, 3**i): 
				if y % 3 == 1: 
					
					# changing its color 
					square[y * stepdown:(y + 1)*stepdown, x * stepdown:(x + 1)*stepdown] = color 

# saving the image produced 
save_file = "sierpinski.jpg"
Image.fromarray(square).save(save_file) 

# displaying it in console 
i = Image.open("sierpinski.jpg") 
i.show() 


In [5]:
# Python code for Julia Fractal 
from PIL import Image 

# driver function 
if __name__ == "__main__": 
	
	# setting the width, height and zoom 
	# of the image to be created 
	w, h, zoom = 1920,1080,1

	# creating the new image in RGB mode 
	bitmap = Image.new("RGB", (w, h), "white") 

	# Allocating the storage for the image and 
	# loading the pixel data. 
	pix = bitmap.load() 
	
	# setting up the variables according to 
	# the equation to create the fractal 
	cX, cY = -0.7, 0.27015
	moveX, moveY = 0.0, 0.0
	maxIter = 255

	for x in range(w): 
		for y in range(h): 
			zx = 1.5*(x - w/2)/(0.5*zoom*w) + moveX 
			zy = 1.0*(y - h/2)/(0.5*zoom*h) + moveY 
			i = maxIter 
			while zx*zx + zy*zy < 4 and i > 1: 
				tmp = zx*zx - zy*zy + cX 
				zy,zx = 2.0*zx*zy + cY, tmp 
				i -= 1

			# convert byte to RGB (3 bytes), kinda 
			# magic to get nice colors 
			pix[x,y] = (i << 21) + (i << 10) + i*8

	# to display the created fractal 
	bitmap.show() 


KeyboardInterrupt: 

In [6]:
# import the turtle module to use turtle graphics 
import turtle 

# make variables for the right and left containing 'r' and 'l' 
r = 'r'
l = 'l'

# assign our first iteration a right so we can build off of it 
old = r 
new = old 

# for inputs 
iteration = int(input('Enter iteration:')) 
length = int(input('Enter length of each segment:')) 
pencolor = input('Enter pen color:') 
bgcolor = input('Enter background color:') 

# set the number of times we have been creating 
# the next iteration as the first 
cycle = 1

# keep on generating the next iteration until desired iteration is reached 
while cycle<iteration: 
	# add a right to the end of the old iteration and save it to the new 
	new = (old) + (r) 
	# flip the old iteration around(as in the first charicter becomes last) 
	old = old[::-1] 
	# cycling through each character in the flipped old iteration: 
	for char in range(0, len(old)): 
		# if the character is a right: 
		if old[char] == r: 
			# change it to a left 
			old = (old[:char])+ (l) + (old[char + 1:]) 
		# otherwise, if it's a left: 
		elif old[char] == l: 
			#change it to a right 
			old = (old[:char]) + (r) + (old[char + 1:]) 
	# add the modified old to the new iteration 
	new = (new) + (old) 

	# save the new iteration to old as well for use next cycle 
	old = new 

	# advance cycle variable to keep track of the number of times it's been done 
	cycle = cycle + 1


printans = input('Display r/l form?(y/n):') 
if printans =='y': 
	print(new) 
	
# for not show the turtle icon when drawing 
turtle.ht() 
turtle.speed(0) 
turtle.color(pencolor) 
turtle.bgcolor(bgcolor) 
turtle.forward(length) 

# cycling through all the characters in the iteration 
for char in range(0, len(new)): 
	# if the character is a right: 
	if new[char] == (r): 
		turtle.right(90) 
		turtle.forward(length) 
	# otherwise, if the character is a left: 
	elif new[char] == (l):	 
		turtle.left(90) 
		turtle.forward(length) 


Enter iteration: 4
Enter length of each segment: 4
Enter pen color: 4
Enter background color: 4
Display r/l form?(y/n): y


rrlrrllrrrllrll


Terminator: 

In [16]:
from numba import cuda
print(cuda.gpus)
numba.cuda.select_device(0)

<Managed Device 0>


IndexError: list index out of range

In [17]:
#https://nyu-cds.github.io/python-numba/05-cuda/
from __future__ import division
from numba import cuda
import numpy
import math

# CUDA kernel
@cuda.jit
def matmul(A, B, C):
    """Perform matrix multiplication of C = A * B
    """
    row, col = cuda.grid(2)
    if row < C.shape[0] and col < C.shape[1]:
        tmp = 0.
        for k in range(A.shape[1]):
            tmp += A[row, k] * B[k, col]
        C[row, col] = tmp
        
# Host code

# Initialize the data arrays
A = numpy.full((24, 12), 3, numpy.float) # matrix containing all 3's
B = numpy.full((12, 22), 4, numpy.float) # matrix containing all 4's

# Copy the arrays to the device
A_global_mem = cuda.to_device(A)
B_global_mem = cuda.to_device(B)

# Allocate memory on the device for the result
C_global_mem = cuda.device_array((24, 22))

# Configure the blocks
threadsperblock = (16, 16)
blockspergrid_x = int(math.ceil(A.shape[0] / threadsperblock[0]))
blockspergrid_y = int(math.ceil(B.shape[1] / threadsperblock[1]))
blockspergrid = (blockspergrid_x, blockspergrid_y)

# Start the kernel 
matmul[blockspergrid, threadsperblock](A_global_mem, B_global_mem, C_global_mem)

# Copy the result back to the host
C = C_global_mem.copy_to_host()

print(C)

[[144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144.
  144. 144. 144. 144. 144. 144. 144. 144.]
 [144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144.
  144. 144. 144. 144. 144. 144. 144. 144.]
 [144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144.
  144. 144. 144. 144. 144. 144. 144. 144.]
 [144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144.
  144. 144. 144. 144. 144. 144. 144. 144.]
 [144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144.
  144. 144. 144. 144. 144. 144. 144. 144.]
 [144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144.
  144. 144. 144. 144. 144. 144. 144. 144.]
 [144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144.
  144. 144. 144. 144. 144. 144. 144. 144.]
 [144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144.
  144. 144. 144. 144. 144. 144. 144. 144.]
 [144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144. 144.
  144. 1

In [18]:
from __future__ import division
from numba import cuda, float32
import numpy
import math

# Controls threads per block and shared memory usage.
# The computation will be done on blocks of TPBxTPB elements.
TPB = 16

@cuda.jit
def fast_matmul(A, B, C):
    """
    Perform matrix multiplication of C = A * B
    Each thread computes one element of the result matrix C
    """

    # Define an array in the shared memory
    # The size and type of the arrays must be known at compile time
    sA = cuda.shared.array(shape=(TPB, TPB), dtype=float32)
    sB = cuda.shared.array(shape=(TPB, TPB), dtype=float32)

    x, y = cuda.grid(2)
    
    tx = cuda.threadIdx.x
    ty = cuda.threadIdx.y
    
    if x >= C.shape[0] and y >= C.shape[1]:
        # Quit if (x, y) is outside of valid C boundary
        return

    # Each thread computes one element in the result matrix.
    # The dot product is chunked into dot products of TPB-long vectors.
    tmp = 0.
    for i in range(int(A.shape[1] / TPB)):
        # Preload data into shared memory
        sA[tx, ty] = A[x, ty + i * TPB]
        sB[tx, ty] = B[tx + i * TPB, y]

        # Wait until all threads finish preloading
        cuda.syncthreads()

        # Computes partial product on the shared memory
        for j in range(TPB):
            tmp += sA[tx, j] * sB[j, ty]

        # Wait until all threads finish computing
        cuda.syncthreads()

    C[x, y] = tmp

# The data array
A = numpy.full((TPB*2, TPB*3), 3, numpy.float) # [32 x 48] matrix containing all 3's
B = numpy.full((TPB*3, TPB*1), 4, numpy.float) # [48 x 16] matrix containing all 4's

A_global_mem = cuda.to_device(mat1)
B_global_mem = cuda.to_device(mat2)
C_global_mem = cuda.device_array((TPB*2, TPB*1)) # [32 x 16] matrix result

# Configure the blocks
threadsperblock = (TPB, TPB)
blockspergrid_x = int(math.ceil(A.shape[0] / threadsperblock[1]))
blockspergrid_y = int(math.ceil(B.shape[1] / threadsperblock[0]))
blockspergrid = (blockspergrid_x, blockspergrid_y)

# Start the kernel 
fast_matmul[blockspergrid, threadsperblock](A_global_mem, B_global_mem, C_global_mem)
res = C_global_mem.copy_to_host()

print(res)

NameError: name 'mat1' is not defined

In [3]:
#https://thedatafrog.com/en/make-python-fast-numba/
import numpy as np
from numba import njit
import math

def std(xs):
  # compute the mean
  mean = 0
  for x in xs: 
    mean += x
  mean /= len(xs)
  # compute the variance
  ms = 0
  for x in xs:
     ms += (x-mean)**2
  variance = ms / len(xs)
  std = math.sqrt(variance)
  return std

a = np.random.normal(0, 1, 10000000)
#std(a)
#%timeit std(a)
##13.9 s ± 566 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

##1.000286796167372

c_std = njit(std)
c_std(a)
%timeit c_std(a)
##40.8 ms ± 340 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


51.5 ms ± 768 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
import numba

In [43]:
import timeit
import random
import numpy as np
x = np.random.random(1_000_000)
y = np.random.random(1_000_000)
print(x)
print(x)

def mcp0(x, y):
   acc = np.sum(x ** 2 + y ** 2 < 1)
   return 4 * acc / len(x)

#%timeit mcp0(x, y)
#print(mcp0(x, y))

@numba.jit
def mcp(x, y):
   acc = np.sum(x ** 2 + y ** 2 < 1)
   return 4 * acc / len(x)

%timeit mcp(x, y)
#32.9 ms ± 576 µs per loop (mean ± std. dev. of 7 runs, 10 loops each) -> CPU
#1.69 ms ± 47.6 µs per loop (mean ± std. dev. of 7 runs, 1 loop each) -> GPU

print(mcp(x, y))
#3.1412520000000002 -> CPU 
#3.141308 -> GPU
#3.141468

[ 0.19688451  0.95178969  0.41837853 ...,  0.75325694  0.50432418
  0.67023501]
[ 0.19688451  0.95178969  0.41837853 ...,  0.75325694  0.50432418
  0.67023501]
1.55 ms ± 121 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.14472


In [57]:
import random
import numpy as np
#from numpy.random import default_rng
#from numpy.random import Generator, PCG64
#rng = np.random.default_rng()
#rng.permutation(10)

numre = np.arange(100).reshape((10, 10))
#numre = np.arange(25).reshape((5, 5))
#numre = np.arange(9).reshape((3, 3))
rng = np.random.random(1)
print(numre)
print(rng)

#print(np.permutation(rng))
#rng = np.random.default_rng()
#rng.permutation(10)
#arr = np.arange(9).reshape((3, 3))
#rng.permutation(arr)
#array([[6, 7, 8], # random
#       [0, 1, 2],
#       [3, 4, 5]])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[ 0.54330889]


In [63]:
#from numpy import *
import numpy as np
#A = np.random.random(4) #matrix('1.0 2.0; 3.0 4.0')
#B = np.random.random(4)
A = np.matrix('1.0 2.0; 3.0 4.0')
B = np.matrix('5.0 6.0; 7.0 5.0')
print(A)
print(B)
np.concatenate((A, B))


[[ 1.  2.]
 [ 3.  4.]]
[[ 5.  6.]
 [ 7.  5.]]


matrix([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  5.]])

In [62]:
# Advanced combining
import numpy as np

# Data
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8')
print('Original Matrices')
print(A)
print(B)

# Getting the size
shA=np.shape(A)
shB=np.shape(B)
rowTot=shA[0]+shB[0]
colTot=shA[1]+shB[1]
rowMax=np.max((shA[0],shB[0]))
colMax=np.max((shA[1],shB[1]))

# Allocate zeros to C
CVert=np.zeros((rowTot,colMax)).astype('int')
CHorz=np.zeros((rowMax,colTot)).astype('int')
CDiag=np.zeros((rowTot,colTot)).astype('int')

# Replace C
CVert[0:shA[0],0:shA[1]]=A
CVert[shA[0]:rowTot,0:shB[1]]=B
print('Vertical Combine')
print(CVert)

CHorz[0:shA[0],0:shA[1]]=A
CHorz[0:shB[0],shA[1]:colTot]=B
print('Horizontal Combine')
print(CHorz)

CDiag[0:shA[0],0:shA[1]]=A
CDiag[shA[0]:rowTot,shA[1]:colTot]=B
print('Diagonal Combine')
print(CDiag)

Original Matrices
[[1 2 3]
 [4 5 6]]
[[7 8]]
Vertical Combine
[[1 2 3]
 [4 5 6]
 [7 8 0]]
Horizontal Combine
[[1 2 3 7 8]
 [4 5 6 0 0]]
Diagonal Combine
[[1 2 3 0 0]
 [4 5 6 0 0]
 [0 0 0 7 8]]


In [72]:
import timeit
import math
import numba as nb
import timeit

LOOKUP_TABLE = np.array([
    1, 1, 2, 6, 24, 120, 720, 5040, 40320,
    362880, 3628800, 39916800, 479001600,
    6227020800, 87178291200, 1307674368000,
    20922789888000, 355687428096000, 6402373705728000,
    121645100408832000, 2432902008176640000], dtype='int64')

@nb.jit
def fast_factorial(n):
    if n > 20:
        raise ValueError
    return LOOKUP_TABLE[n]

def loop_python():
    for i in range(10000):
        for n in range(21):
            math.factorial(n)

@nb.njit
def loop_numba():
    for i in range(10000):
        for n in range(21):
            fast_factorial(n)

#%timeit math.factorial(10)
#%timeit fast_factorial(10)

%timeit loop_python()
#%timeit loop_numba()

#273 ns ± 52.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
#3.3 µs ± 1.74 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

#87.7 ms ± 3.62 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

#The slowest run took 11.25 times longer than the fastest. This could mean that an intermediate result is being cached.
#1.07 µs ± 1.41 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


#Kernel Kaggle
#38.6 ms ± 705 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
#The slowest run took 6.51 times longer than the fastest. This could mean that an intermediate result is being cached.
#759 ns ± 786 ns per loop (mean ± std. dev. of 7 runs, 1 loop each)


87.7 ms ± 3.62 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
from __future__ import absolute_import, division, print_function, unicode_literals
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 
import timeit
import math
#import numba as nb
import timeit
#import numpy as np # linear algebra
#import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
#for dirname, _, filenames in os.walk('/kaggle/input'):
#    for filename in filenames:
#        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

LOOKUP_TABLE = np.array([
    1, 1, 2, 6, 24, 120, 720, 5040, 40320,
    362880, 3628800, 39916800, 479001600,
    6227020800, 87178291200, 1307674368000,
    20922789888000, 355687428096000, 6402373705728000,
    121645100408832000, 2432902008176640000], dtype='int64')

#@nb.jit
def fast_factorial(n):
    if n > 20:
        raise ValueError
    return LOOKUP_TABLE[n]

def loop_python():
    for i in range(10000):
        for n in range(21):
            math.factorial(n)

#@nb.njit
def loop_numba():
    for i in range(10000):
        for n in range(21):
            fast_factorial(n)

#%timeit math.factorial(10)
#%timeit fast_factorial(10)

#%timeit loop_python()
#loop_numba()

print('bismillah...')
print('Num GPUs Available:  ', len(tf.config.experimental.list_physical_devices('GPU')))

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set

ImportError: numpy.core._multiarray_umath failed to import

ImportError: numpy.core.umath failed to import

In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

ModuleNotFoundError: No module named 'tensorflow'

In [13]:
import timeit
import math
import numba as nb
import numpy as np
LOOKUP_TABLE = np.array([
    1, 1, 2, 6, 24, 120, 720, 5040, 40320,
    362880, 3628800, 39916800, 479001600,
    6227020800, 87178291200, 1307674368000,
    20922789888000, 355687428096000, 6402373705728000,
    121645100408832000, 2432902008176640000], dtype='int64')

@nb.jit
def fast_factorial(n):
    if n > 20:
        raise ValueError
    return LOOKUP_TABLE[n]

def loop_python():
    for i in range(10000):
        for n in range(21):
            math.factorial(n)

@nb.njit
def loop_numba():
    for i in range(10001):
        for n in range(21):
            fast_factorial(n)

#%timeit math.factorial(10)
#%timeit fast_factorial(10)

#%timeit loop_python()
%timeit loop_numba()

#273 ns ± 52.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
#3.3 µs ± 1.74 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

#87.7 ms ± 3.62 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

#The slowest run took 11.25 times longer than the fastest. This could mean that an intermediate result is being cached.
#1.07 µs ± 1.41 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


#Kernel Kaggle
#38.6 ms ± 705 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
#The slowest run took 6.51 times longer than the fastest. This could mean that an intermediate result is being cached.
#759 ns ± 786 ns per loop (mean ± std. dev. of 7 runs, 1 loop each)
print('Bismillah')

The slowest run took 19.00 times longer than the fastest. This could mean that an intermediate result is being cached.
800 ns ± 1.23 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
Bismillah


In [16]:
#https://numba.pydata.org/numba-doc/dev/user/5minguide.html
from numba import jit
import numpy as np

x = np.arange(100).reshape(10, 10)

@jit(nopython=True) # Set "nopython" mode for best performance, equivalent to @njit
def go_fast(a): # Function is compiled to machine code when called the first time
    trace = 0
    for i in range(a.shape[0]):   # Numba likes loops
        trace += np.tanh(a[i, i]) # Numba likes NumPy functions
    return a + trace              # Numba likes NumPy broadcasting

print(go_fast(x))

[[   9.   10.   11.   12.   13.   14.   15.   16.   17.   18.]
 [  19.   20.   21.   22.   23.   24.   25.   26.   27.   28.]
 [  29.   30.   31.   32.   33.   34.   35.   36.   37.   38.]
 [  39.   40.   41.   42.   43.   44.   45.   46.   47.   48.]
 [  49.   50.   51.   52.   53.   54.   55.   56.   57.   58.]
 [  59.   60.   61.   62.   63.   64.   65.   66.   67.   68.]
 [  69.   70.   71.   72.   73.   74.   75.   76.   77.   78.]
 [  79.   80.   81.   82.   83.   84.   85.   86.   87.   88.]
 [  89.   90.   91.   92.   93.   94.   95.   96.   97.   98.]
 [  99.  100.  101.  102.  103.  104.  105.  106.  107.  108.]]


In [17]:
from numba import jit
import numpy as np
import time

x = np.arange(100).reshape(10, 10)

@jit(nopython=True)
def go_fast(a): # Function is compiled and runs in machine code
    trace = 0
    for i in range(a.shape[0]):
        trace += np.tanh(a[i, i])
    return a + trace

# DO NOT REPORT THIS... COMPILATION TIME IS INCLUDED IN THE EXECUTION TIME!
start = time.time()
go_fast(x)
end = time.time()
print("Elapsed (with compilation) = %s" % (end - start))

# NOW THE FUNCTION IS COMPILED, RE-TIME IT EXECUTING FROM CACHE
start = time.time()
go_fast(x)
end = time.time()
print("Elapsed (after compilation) = %s" % (end - start))


Elapsed (with compilation) = 0.5176949501037598
Elapsed (after compilation) = 0.0
